lib/night_in_salem_web/router.ex
defmodule NightInSalemWeb.Router do
  use NightInSalemWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", NightInSalemWeb do
    pipe_through :browser # Use the default browser stack

    resources "/player", GameSessionPlayerController, only: [:new, :create]
    resources "/", GameSessionController
  end

  # Other scopes may use custom stacks.
  # scope "/api", NightInSalemWeb do
  #   pipe_through :api
  # end
end

lib/night_in_salem_web/controllers/game_player_controller.ex
defmodule NightInSalemWeb.GamePlayerController do
  use NightInSalemWeb, :controller
  alias NightInSalem.GameMasterSupervisor
  alias NightInSalem.GameMaster

  def new(conn, _params) do
    render conn, "new.html"
  end

  def create(conn, %{ "game_session" => %{ "player_name" => player_name, "game_key" => game_key } }) do
    GameMaster.add_player(game_key, player_name)
    conn
      |> put_session(:player_name, player_name)
      |> put_session(:game_key, game_key)
      |> redirect(to: game_session_path(conn, :show, game_key))
  end


end

lib/night_in_salem_web/templates/game_player/new.html.eex
<%= form_for @conn, game_player_path(@conn, :create), [as: :game_session, method: :post], fn f -> %>
  <%= text_input f, :game_key, placeholder: "Game Key" %>
  <%= text_input f, :player_name, placeholder: "Player Name" %>
  <%= submit "Join Game" %>
<% end %>