lib/night_in_salem_web/router.ex
defmodule NightInSalemWeb.Router do
  use NightInSalemWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", NightInSalemWeb do
    pipe_through :browser # Use the default browser stack

    resources "/player", GameSessionPlayerController, only: [:new, :create]
    resources "/", GameSessionController
  end

  # Other scopes may use custom stacks.
  # scope "/api", NightInSalemWeb do
  #   pipe_through :api
  # end
end

lib/night_in_salem_web/controllers/game_session_controller.ex
defmodule NightInSalemWeb.GameSessionController do
  use NightInSalemWeb, :controller
  alias NightInSalem.GameMasterSupervisor
  alias NightInSalem.GameMaster

  def index(conn, _params) do
    render conn, "index.html"
  end

  def new(conn, _params) do
    render conn, "new.html"
  end

  def create(conn, %{ "game_session" => %{ "player_name" => player_name } }) do
    game_key = GameMasterSupervisor.start_game
    GameMaster.add_player(game_key, player_name)
    conn
      |> put_session(:player_name, player_name)
      |> put_session(:game_key, game_key)
      |> redirect(to: game_session_path(conn, :show, game_key))
  end

  def show(conn, %{ "id" => game_key }) do
    player_name = get_session(conn, :player_name)
    show_for_player(conn, game_key, player_name)
  end

  defp show_for_player(conn, game_key, nil) do
    conn
      |> redirect(to: game_session_path(conn, :edit, game_key))
  end

  defp show_for_player(conn, game_key, player_name) do
    render conn, "show.html", player_name: player_name, game_key: game_key, user_token: Phoenix.Token.sign(conn, "player name", player_name)
  end

  def edit(conn, %{ "id" => game_key }) do
    render conn, "edit.html", game_key: game_key
  end

  def update(conn, %{ "game_session" => %{ "player_name" => player_name }, "id" => game_key }) do
    GameMaster.add_player(game_key, player_name)
    conn
      |> put_session(:player_name, player_name)
      |> put_session(:game_key, game_key)
      |> redirect(to: game_session_path(conn, :show, game_key))
  end
end

lib/night_in_salem_web/views/game_session_view.ex
defmodule NightInSalemWeb.GameSessionView do
  use NightInSalemWeb, :view
end

lib/night_in_salem_web/templates/game_session/_form.html.eex
<%= text_input @form, :player_name, placeholder: "Player Name" %>

lib/night_in_salem_web/templates/game_session/edit.html.eex
<%= form_for @conn, game_session_path(@conn, :update, @game_key), [as: :game_session, method: :patch], fn f -> %>
  <%= render "_form.html", form: f %>
  <%= submit "Join Game" %>
<% end %>

lib/night_in_salem_web/templates/game_session/index.html.eex
<%= link("New Session", to: game_session_path(@conn, :new)) %>
<br>
<%= link("Join Session", to: game_session_player_path(@conn, :new)) %>
<%#= link("Join Session", to: "/game_session/1/edit") %>

lib/night_in_salem_web/templates/game_session/new.html.eex
<%= form_for @conn, game_session_path(@conn, :create), [as: :game_session], fn f -> %>
  <%= render "_form.html", form: f %>
  <%= submit "New Game" %>
<% end %>

lib/night_in_salem_web/templates/game_session/show.html.eex
<h2>Hi <%= @player_name %></h2>

<p>
  This session is <%= @game_key %>, use the 📋 button below to copy the address of this game to your clipboard so you can send it to your friends
</p>
<p class="game-link-container">
  <input class="copy-link game-link" id="game-link" type="text" readonly value="<%=game_session_url(@conn, :show, @game_key)%>"><span class="copy-link clipboard" data-target="game-link">📋</span>
</p>

<h2>Players:</h2>
<div id="users"></div>